Server:
  Port: "8000"

Registry:
  UserMessage: "Разработчики получат информацию об ошибке автоматически." # Текст, который будет показан пользователю в качестве дополнительной информации об ошибке
  DumpType: 1   # Тип дампа, который нужно приложить к отчету об ошибке (аналогичен значению атрибута type элемента dump файла logcfg.xml)
  Timeout: 20
  
Projects:
  - Name: ""
    ID: ""
    Service:
      Use: true
      Url: ""
      IimeOut: 20 #Минут
      Credintials:
        UserName: ""
        Password: ""
      Cache:
        Use: true
        Expiration: 60 #Минут
      Exeptions:
        Use: true
        Cache:
          Use: true
          Expiration: 1440 #24 часа
      Test: 
        UserName: "" 
    Session:
      Use: true
      Duration: 1440 #Минут
    Sentry:
      Dsn: ""
      IimeOut: 5 #Секунд
      Environment: "dev"
      Platform: "Other"
      ContextAround:
        Use: true
        Quantity: 6
        Cache:
          Use: true
          Expiration: 60
      Attachments:
        Use: false
        Сompress:
          Use: true
          Percent: 30
      SendingCache:
          Use: true
          Expiration: 3
    Git:
      Use: true
      Url: ""
      Path: ""
      Token: ""
      Branch: "master" 
      SourceCodeRoot: "config"
    Extentions:
      - ""
      - ""

Redis:
  Use: true
  Addr: ""
  DB: 15
  Credintials:
    UserName: ""
    Password: ""

SentryMetrics: 
  Port: 9790
  Interval: 180 #Секунд
  Sentry:
    Url: ""
    Org: ""
    Token: ""
    Timeout: 60 
  Metrics:
    - Use: true
      Name: "Sessions"
      Projects:
      - Id: "2"
        Name: ""
      - Id: "12"
        Name: ""
      - Id: "11"
        Name: ""

Log:
  Debug: true
  Level: 5            # Уровень логирования от 2 до 5, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг
  OutputInFile: false # включить логирование в каталог LogDir
  Dir: "logs"         # каталог логов
  
DeleteTempFiles: false # Удалать файлы из web/temp

Sentry:
  Use: false # Включить sentry для отлова внутренних ошибок
  Dsn: ""
  Environment: "Debug"
  AttachStacktrace: true
  TracesSampleRate: 1.0
  EnableTracing: true
  Debug: true